name: Android Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Android
    uses: ./.github/workflows/build.yml
    with:
        name: Android
        os: macos-15
        setupCommand: sh ./setup/unix.sh
        buildArgs: "android -final -arm64"
        artifactName: androidBuild
        artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"