name: Android Build

on:
  push:
    branches: [main]
    paths:
      - 'source/**'
      - 'assets/**'
      - 'Project.xml'
      - 'setup/**'
      - '.github/workflows/**'
      - 'key.keystore'
  workflow_dispatch:

concurrency:
  group: android-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Android
    uses: ./.github/workflows/build.yml
    with:
        name: Android
        os: macos-15
        setupCommand: sh ./setup/unix.sh
        buildArgs: "android -debug -arm64"
        artifactName: androidBuild
        artifactPath: "export/debug/android/bin/app/build/outputs/apk/debug/*.apk"